name: Sapper Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Sapper Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Checking Node
        run: node -v
      - name: Checking NPM
        run: npm -v
      - name: Building Sapper
        run: |
          npm install
          npm run build
        working-directory: 
